name: Hardhat Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Start Hardhat Node
        run: npx hardhat node &
        env:
          HARDHAT_NETWORK: hardhat

      - name: Run Tests
        run: npx hardhat test --network hardhat
